python to_c_array.py TNG100 > baryons.h
python to_c_array.py mb2 >> baryons.h
python to_c_array.py eagle >> baryons.h
python to_c_array.py illustris >> baryons.h
python to_c_array.py HzAGN >> baryons.h
python to_c_array.py cowls_AGN_T80 >> baryons.h
python to_c_array.py cowls_AGN_T85 >> baryons.h
python to_c_array.py cowls_AGN_T87 >> baryons.h
python to_c_array.py BAHAMAS_T78 >> baryons.h
python to_c_array.py BAHAMAS_T76 >> baryons.h
python to_c_array.py BAHAMAS_T80 >> baryons.h